//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrakeOil
    {
        public int BrakeOilId { get; set; }
        public string BrakeOilName { get; set; }
        public string BrakeOilCompanyName { get; set; }
        public double BrakeOilPrice { get; set; }
    }
}
