//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.OilChangeRecords = new HashSet<OilChangeRecord>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerMiddleName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerMobileNumber1 { get; set; }
        public string CustomerMobileNumber2 { get; set; }
        public string CustomerLandline { get; set; }
        public string CustomerEmailAddress { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<System.DateTime> CustomerCreatedDate { get; set; }
        public string CustomerDescription { get; set; }
    
        public virtual ICollection<OilChangeRecord> OilChangeRecords { get; set; }
    }
}
