//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OilChangeRecord
    {
        public int OilChangeRecordId { get; set; }
        public Nullable<int> OilCustomerId { get; set; }
        public Nullable<int> OilId { get; set; }
        public Nullable<int> CustomerVehicleId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
