//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OilFilterMakerCompany
    {
        public OilFilterMakerCompany()
        {
            this.OilFilters = new HashSet<OilFilter>();
        }
    
        public int OilFilterMakerCompanyId { get; set; }
        public string OilFilterMakerCompanyName { get; set; }
        public string OilFilterMakerCompanyDescription { get; set; }
    
        public virtual ICollection<OilFilter> OilFilters { get; set; }
    }
}
