//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OilFilter
    {
        public int OilFilterId { get; set; }
        public string OilFilterName { get; set; }
        public double OilFilterPrice { get; set; }
        public Nullable<int> OilFilterMakerCompanyId { get; set; }
    
        public virtual OilFilterMakerCompany OilFilterMakerCompany { get; set; }
    }
}
