//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerSterringOil
    {
        public int PowerStereringOilId { get; set; }
        public string PowerSterringOilName { get; set; }
        public string PowerSterringOilCompany { get; set; }
        public double PowerSterringOilPrice { get; set; }
    }
}
