//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModelMaker
    {
        public VehicleModelMaker()
        {
            this.CustomerVehicles = new HashSet<CustomerVehicle>();
        }
    
        public long VehicleId { get; set; }
        public Nullable<long> VehicleMakerId { get; set; }
        public string VehicleModelName { get; set; }
        public Nullable<long> FuilingTypeId { get; set; }
    
        public virtual ICollection<CustomerVehicle> CustomerVehicles { get; set; }
    }
}
