//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleMaker
    {
        public int VehicleMakerId { get; set; }
        public string VehicleMakerName { get; set; }
        public Nullable<System.DateTime> RecordCreatedDate { get; set; }
        public Nullable<int> RecCreatedBy { get; set; }
    }
}
